export enum Status {
    OK = 200,
    NOT_FOUND = 404,
    BAD_REQUEST = 400,
    CREATED = 201,
    INTERNAL_SERVER_ERROR = 500
}

export enum Code {
    OK = 'OK',
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    CREATED = 'CREATED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}